import type { ExplanationFactorId, ExplanationLexicon } from "@/domain/explanation";

const explanationFactorLabels = {
  action: "アクション",
  fantasy: "ファンタジー",
  historical: "歴史もの",
  scienceFiction: "SF",
  mystery: "ミステリー",
  sports: "スポーツ",
  comedy: "ギャグ・コメディ",
  horror: "ホラー",
  sliceOfLife: "日常",
  romance: "恋愛要素",
  adventure: "冒険",
  combat: "戦闘",
  martialArts: "武術",
  war: "戦争",
  politics: "政治",
  survival: "サバイバル",
  investigation: "捜査・調査",
  dungeon: "ダンジョン攻略",
  crafting: "ものづくり",
  cooking: "料理",
  territoryManagement: "領地運営",
  tournament: "大会・トーナメント",
  revenge: "復讐",
  timeTravel: "タイムトラベル",
  reincarnation: "転生",
  school: "学園",
  workplace: "仕事・職場",
  sportsCompetition: "スポーツ競技",
  foundFamily: "仲間との家族的な絆",
  historicalReconstruction: "歴史再現",
  postApocalypse: "終末世界",
  exploration: "探索",
  progression: "成長・報酬の積み重ね",
  problemSolving: "頭脳で解決する話",
  strategy: "戦略的な展開",
  pacing: "テンポの速さ",
  mysteryReveal: "謎解き・伏線",
  worldBuilding: "世界観の作り込み",
  characterArcWeight: "人物の変化・ドラマ",
  relationshipStructure: "群像劇・関係の広がり",
  darkness: "ダークな世界観",
  mentalStress: "精神的な重さ",
  emotionalWarmth: "あたたかさ・癒やし",
  artRealism: "リアル寄りの絵",
  artDensity: "描き込みの密度",
  visualSoftness: "やわらかい絵柄",
  motionImpact: "迫力・スピード感",
} as const satisfies Readonly<Record<ExplanationFactorId, string>>;

export const explanationLexicon = {
  factorLabels: explanationFactorLabels,
  clusterLabels: {
    tacticalThinking: "頭脳で解決する展開",
    relationshipAppeal: "人物の変化と関係性",
    toneLoad: "物語の重さ",
  },
  confidenceLabels: {
    high: "高い",
    normal: "ふつう",
    low: "低め(データ収集中)",
  },
  templates: {
    positiveWithAnchor: "『{anchorTitle}』で好きだった「{factorLabel}」に近い作品です。",
    positiveWithoutAnchor: "「{factorLabel}」があなたの好みに合う作品です。",
    positiveLowerAxisAdjustment: "「{factorLabel}」が控えめな点が、あなたの好みに合う作品です。",
    cautionSimilarityWithAnchor:
      "ただし「{factorLabel}」は、『{anchorTitle}』で好きだった傾向と少し異なります。",
    cautionSimilarityWithoutAnchor: "ただし「{factorLabel}」は、あなたの好みと少し異なります。",
    baselineGenreWithAnchor: "『{anchorTitle}』と「{factorLabel}」が共通しています。",
    baselineGenreWithoutAnchor: "「{factorLabel}」のジャンル一致を順位に反映しています。",
    baselineMarketObserved: "第1巻のレビュー情報を順位に反映しています。",
    baselineMaturity: "刊行の蓄積を順位に反映しています。",
  },
} as const satisfies ExplanationLexicon;

const wantToReadScale = [
  { value: 1, label: "まったく読みたくない" },
  { value: 2, label: "あまり読みたくない" },
  { value: 3, label: "どちらともいえない" },
  { value: 4, label: "読みたい" },
  { value: 5, label: "とても読みたい" },
] as const;

const agreementScale = [
  { value: 1, label: "まったく当てはまらない" },
  { value: 2, label: "あまり当てはまらない" },
  { value: 3, label: "どちらともいえない" },
  { value: 4, label: "当てはまる" },
  { value: 5, label: "とても当てはまる" },
] as const;

export const appName = "konocomics";

export const g2HarnessStrings = {
  metadata: {
    title: "ブラインドテスト | konocomics",
    description: "2つのおすすめ一覧を比較するローカル専用ブラインドテストです。",
  },
  entry: {
    eyebrow: "ローカル専用ブラインドテスト",
    title: "おすすめを、説明の前後で比べます。",
    description:
      "2つのおすすめ一覧を見て、作品ごとの印象と、どちらが自分に合うかを回答します。回答途中の内容は保存も送信もされません。",
    choose: "入口を選んでください",
    humanTitle: "参加者として回答する",
    humanDescription: "人によるブラインドテストの結果を作成します。",
    syntheticPilotTitle: "動作確認を行う",
    syntheticPilotDescription:
      "ブラウザから結果ファイルまでの流れを確認します。人の回答としては集計されません。",
  },
  mode: {
    human: "参加者用",
    syntheticPilot: "動作確認用",
  },
  progress: {
    label: "回答の進み具合",
    input: "入力",
    before: "説明前",
    after: "説明後",
    complete: "完了",
  },
  input: {
    title: "テストを始める",
    description: "事前に用意したプロフィールを、このブラウザ内だけで読み込みます。",
    participantIdLabel: "参加者ID",
    participantIdHint:
      "英小文字・数字・ハイフンだけの匿名IDを入力してください。氏名やメールアドレスは入力しないでください。",
    profileLabel: "プロフィールJSON",
    profileHint: "自分の参加者IDと同じ profileId を持つファイルを選んでください。",
    privacy:
      "ファイルと回答は外部へ送信されません。ページを閉じるか再読み込みすると、入力途中の内容は消えます。",
    submit: "おすすめ一覧を作る",
    loading: "おすすめ一覧を準備しています…",
  },
  before: {
    title: "説明を見る前の回答",
    description:
      "リストA・リストBの順位を確認し、重複を除いた各作品について一度だけ回答してください。",
    sharedResponse:
      "両方のリストにある作品も、ここでは1回だけ回答します。次へ進むと回答は変更できません。",
    sharedAnswerRecorded: "この作品の回答は、先に表示されたリストと共有されています。",
    familiarityQuestion: "この作品を知っていましたか？",
    familiarity: {
      read: "読んだことがある",
      knownUnread: "知っているが未読",
      unknown: "知らなかった",
    },
    wantToReadQuestion: "今、この作品を読みたいですか？",
    wantToReadScale,
    preferenceQuestion: "説明を見る前のおすすめ一覧として、どちらが自分に合っていますか？",
    preference: {
      A: "リストA",
      B: "リストB",
      tie: "同じくらい",
    },
    submit: "説明前の回答を確定する",
    incomplete: "すべての質問に回答すると次へ進めます。",
  },
  after: {
    title: "おすすめ理由を見た後の回答",
    description:
      "順位はそのままです。各おすすめ理由を読み、一覧に現れる作品ごとに回答してください。",
    explanationHeading: "おすすめ理由",
    noExplanation: "説明はありません。",
    wantToReadQuestion: "今、この作品を読みたいですか？",
    wantToReadScale,
    agreementQuestion: "このおすすめ理由は、あなたの好みとの関係を正しく説明していますか？",
    agreementScale,
    submit: "最終回答を確定する",
    incomplete: "すべての質問に回答すると最終回答を確定できます。",
  },
  lists: {
    A: "リストA",
    B: "リストB",
    rankSuffix: "位",
    coverUnavailable: "表紙画像なし",
    creatorPrefix: "作者",
  },
  complete: {
    title: "回答が完了しました",
    description:
      "ここで初めて、各リストの作り方を確認できます。結果JSONをダウンロードし、集計担当者へ渡してください。",
    debriefHeading: "リストの内訳",
    taste: "Taste Engine",
    baseline: "Baseline",
    download: "結果JSONをダウンロード",
    downloaded: "結果JSONをダウンロードしました。",
    restart: "最初からやり直す",
  },
  errors: {
    participantId: "参加者IDは、1〜64文字の英小文字・数字・ハイフンで入力してください。",
    profileRequired: "プロフィールJSONを選んでください。",
    profileTooLarge: "プロフィールJSONは1 MiB以下にしてください。",
    profileEncoding: "プロフィールJSONはBOMなしのUTF-8で保存してください。",
    profileJson: "プロフィールJSONを読み取れませんでした。内容を確認してください。",
    setup:
      "プロフィールを使ってテストを開始できませんでした。参加者IDとプロフィール内容を確認してください。",
    result: "回答結果を作成できませんでした。入力内容を確認してください。",
  },
} as const;

export const strings = {
  appName,
  metadata: {
    description: "マンガの好みを分析し、理由とともに次の一冊を提案します。",
  },
  explanation: explanationLexicon,
  g2Harness: g2HarnessStrings,
  experimentReport: {
    title: "konocomics Taste vs Baseline レポート",
    headings: {
      profile: "プロフィール",
      profileSummary: "入力サマリー",
      tasteTop: "Taste Engine Top 10",
      baselineTop: "Baseline Top 10",
      diagnostic: "診断サマリー",
    },
    fields: {
      catalogVersion: "カタログバージョン",
      factorDictionaryVersion: "ファクター辞書バージョン",
      baselineVersion: "Baseline バージョン",
      profileCount: "プロフィール数",
      anchors: "好みのアンカー",
      negativeSources: "苦手情報の参照元",
      adjustments: "好みの調整",
      score: "スコア",
      confidence: "確信度",
      bestAnchor: "最も近いアンカー",
      positiveReasons: "おすすめ理由",
      caution: "注意点",
      evidenceAnchors: "根拠アンカー",
      penalties: "適用された減点",
      coverage: "カバレッジ警告",
      ledger: "寄与度上位5件",
      reason: "理由",
      bayesianRating: "ベイズ補正レビュー",
      maturity: "刊行蓄積度",
      tasteCount: "Taste 件数",
      baselineCount: "Baseline 件数",
      shrunkCount: "SHRUNK グループ数",
      partialCount: "PARTIAL グループ数",
      reactionWeight: "反応ウェイト",
    },
    ledgerColumns: {
      rank: "順位",
      delta: "寄与",
      source: "source",
      group: "group",
      factorId: "factorId",
      anchorWorkIds: "anchorWorkIds",
      negativeReasonId: "negativeReasonId",
      explainable: "説明対象",
    },
    values: {
      none: "なし",
      yes: "はい",
      no: "いいえ",
    },
    reactionLabels: {
      favorite: "大好き",
      liked: "好き",
    },
    adjustmentLabels: {
      veryLike: "とても好き",
      like: "好き",
      auto: "自動",
      less: "控えめ",
      exclude: "除外",
    },
    negativeReasonLabels: {
      tooSlow: "展開が遅い",
      tooRepetitiveProgression: "成長展開の繰り返しが多い",
      tooDark: "暗すぎる",
      tooStressful: "精神的に重すぎる",
      tooMuchRomance: "恋愛要素が多すぎる",
      tooMuchComedy: "コメディが多すぎる",
      notEnoughSeriousness: "シリアスさが足りない",
      tooComplex: "複雑すぎる",
      artStyleDislike: "絵柄が合わない",
      genericStory: "物語がありきたり",
      powerInflation: "強さのインフレが気になる",
      vagueDislike: "理由を特定できない苦手",
    },
  },
} as const;
