import type { ExplanationFactorId, ExplanationLexicon } from "@/domain/explanation";

const explanationFactorLabels = {
  action: "アクション",
  fantasy: "ファンタジー",
  historical: "歴史もの",
  scienceFiction: "SF",
  mystery: "ミステリー",
  sports: "スポーツ",
  comedy: "ギャグ・コメディ",
  horror: "ホラー",
  sliceOfLife: "日常",
  romance: "恋愛要素",
  adventure: "冒険",
  combat: "戦闘",
  martialArts: "武術",
  war: "戦争",
  politics: "政治",
  survival: "サバイバル",
  investigation: "捜査・調査",
  dungeon: "ダンジョン攻略",
  crafting: "ものづくり",
  cooking: "料理",
  territoryManagement: "領地運営",
  tournament: "大会・トーナメント",
  revenge: "復讐",
  timeTravel: "タイムトラベル",
  reincarnation: "転生",
  school: "学園",
  workplace: "仕事・職場",
  sportsCompetition: "スポーツ競技",
  foundFamily: "仲間との家族的な絆",
  historicalReconstruction: "歴史再現",
  postApocalypse: "終末世界",
  exploration: "探索",
  progression: "成長・報酬の積み重ね",
  problemSolving: "頭脳で解決する話",
  strategy: "戦略的な展開",
  pacing: "テンポの速さ",
  mysteryReveal: "謎解き・伏線",
  worldBuilding: "世界観の作り込み",
  characterArcWeight: "人物の変化・ドラマ",
  relationshipStructure: "群像劇・関係の広がり",
  darkness: "ダークな世界観",
  mentalStress: "精神的な重さ",
  emotionalWarmth: "あたたかさ・癒やし",
  artRealism: "リアル寄りの絵",
  artDensity: "描き込みの密度",
  visualSoftness: "やわらかい絵柄",
  motionImpact: "迫力・スピード感",
} as const satisfies Readonly<Record<ExplanationFactorId, string>>;

const explanation = {
  factorLabels: explanationFactorLabels,
  clusterLabels: {
    tacticalThinking: "頭脳で解決する展開",
    relationshipAppeal: "人物の変化と関係性",
    toneLoad: "物語の重さ",
  },
  confidenceLabels: {
    high: "高い",
    normal: "ふつう",
    low: "低め(データ収集中)",
  },
  templates: {
    positiveWithAnchor: "『{anchorTitle}』で好きだった「{factorLabel}」に近い作品です。",
    positiveWithoutAnchor: "「{factorLabel}」があなたの好みに合う作品です。",
    cautionSimilarityWithAnchor:
      "ただし「{factorLabel}」は、『{anchorTitle}』で好きだった傾向と少し異なります。",
    cautionSimilarityWithoutAnchor: "ただし「{factorLabel}」は、あなたの好みと少し異なります。",
    baselineGenreWithAnchor: "『{anchorTitle}』と「{factorLabel}」が共通しています。",
    baselineGenreWithoutAnchor: "「{factorLabel}」のジャンル一致を順位に反映しています。",
    baselineMarketObserved: "第1巻のレビュー情報を順位に反映しています。",
    baselineMaturity: "刊行の蓄積を順位に反映しています。",
  },
} as const satisfies ExplanationLexicon;

export const strings = {
  appName: "konocomics",
  metadata: {
    description: "マンガの好みを分析し、理由とともに次の一冊を提案します。",
  },
  explanation,
  experimentReport: {
    title: "konocomics Taste vs Baseline レポート",
    headings: {
      profile: "プロフィール",
      profileSummary: "入力サマリー",
      tasteTop: "Taste Engine Top 10",
      baselineTop: "Baseline Top 10",
      diagnostic: "診断サマリー",
    },
    fields: {
      catalogVersion: "カタログバージョン",
      factorDictionaryVersion: "ファクター辞書バージョン",
      baselineVersion: "Baseline バージョン",
      profileCount: "プロフィール数",
      anchors: "好みのアンカー",
      negativeSources: "苦手情報の参照元",
      adjustments: "好みの調整",
      score: "スコア",
      confidence: "確信度",
      bestAnchor: "最も近いアンカー",
      positiveReasons: "おすすめ理由",
      caution: "注意点",
      evidenceAnchors: "根拠アンカー",
      penalties: "適用された減点",
      coverage: "カバレッジ警告",
      ledger: "寄与度上位5件",
      reason: "理由",
      bayesianRating: "ベイズ補正レビュー",
      maturity: "刊行蓄積度",
      tasteCount: "Taste 件数",
      baselineCount: "Baseline 件数",
      shrunkCount: "SHRUNK グループ数",
      partialCount: "PARTIAL グループ数",
      reactionWeight: "反応ウェイト",
    },
    ledgerColumns: {
      rank: "順位",
      delta: "寄与",
      source: "source",
      group: "group",
      factorId: "factorId",
      anchorWorkIds: "anchorWorkIds",
      negativeReasonId: "negativeReasonId",
      explainable: "説明対象",
    },
    values: {
      none: "なし",
      yes: "はい",
      no: "いいえ",
    },
    reactionLabels: {
      favorite: "大好き",
      liked: "好き",
    },
    adjustmentLabels: {
      veryLike: "とても好き",
      like: "好き",
      auto: "自動",
      less: "控えめ",
      exclude: "除外",
    },
    negativeReasonLabels: {
      tooSlow: "展開が遅い",
      tooRepetitiveProgression: "成長展開の繰り返しが多い",
      tooDark: "暗すぎる",
      tooStressful: "精神的に重すぎる",
      tooMuchRomance: "恋愛要素が多すぎる",
      tooMuchComedy: "コメディが多すぎる",
      notEnoughSeriousness: "シリアスさが足りない",
      tooComplex: "複雑すぎる",
      artStyleDislike: "絵柄が合わない",
      genericStory: "物語がありきたり",
      powerInflation: "強さのインフレが気になる",
      vagueDislike: "理由を特定できない苦手",
    },
  },
} as const;
