/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasteRouteImport } from './routes/taste'
import { Route as WorksWorkIdRouteImport } from './routes/works/$workId'
import { Route as WorksExternalRouteImport } from './routes/works/external'
import { Route as ApiRakutenItemRouteImport } from './routes/api/rakuten/item'
import { Route as ApiRakutenSearchRouteImport } from './routes/api/rakuten/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasteRoute = TasteRouteImport.update({
  id: '/taste',
  path: '/taste',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksExternalRoute = WorksExternalRouteImport.update({
  id: '/works/external',
  path: '/works/external',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRakutenItemRoute = ApiRakutenItemRouteImport.update({
  id: '/api/rakuten/item',
  path: '/api/rakuten/item',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRakutenSearchRoute = ApiRakutenSearchRouteImport.update({
  id: '/api/rakuten/search',
  path: '/api/rakuten/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/taste': typeof TasteRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/works/external': typeof WorksExternalRoute
  '/api/rakuten/item': typeof ApiRakutenItemRoute
  '/api/rakuten/search': typeof ApiRakutenSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/taste': typeof TasteRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/works/external': typeof WorksExternalRoute
  '/api/rakuten/item': typeof ApiRakutenItemRoute
  '/api/rakuten/search': typeof ApiRakutenSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/taste': typeof TasteRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/works/external': typeof WorksExternalRoute
  '/api/rakuten/item': typeof ApiRakutenItemRoute
  '/api/rakuten/search': typeof ApiRakutenSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/onboarding'
    | '/recommendations'
    | '/settings'
    | '/taste'
    | '/works/$workId'
    | '/works/external'
    | '/api/rakuten/item'
    | '/api/rakuten/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/onboarding'
    | '/recommendations'
    | '/settings'
    | '/taste'
    | '/works/$workId'
    | '/works/external'
    | '/api/rakuten/item'
    | '/api/rakuten/search'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/onboarding'
    | '/recommendations'
    | '/settings'
    | '/taste'
    | '/works/$workId'
    | '/works/external'
    | '/api/rakuten/item'
    | '/api/rakuten/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SettingsRoute: typeof SettingsRoute
  TasteRoute: typeof TasteRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  WorksExternalRoute: typeof WorksExternalRoute
  ApiRakutenItemRoute: typeof ApiRakutenItemRoute
  ApiRakutenSearchRoute: typeof ApiRakutenSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taste': {
      id: '/taste'
      path: '/taste'
      fullPath: '/taste'
      preLoaderRoute: typeof TasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/external': {
      id: '/works/external'
      path: '/works/external'
      fullPath: '/works/external'
      preLoaderRoute: typeof WorksExternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rakuten/item': {
      id: '/api/rakuten/item'
      path: '/api/rakuten/item'
      fullPath: '/api/rakuten/item'
      preLoaderRoute: typeof ApiRakutenItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rakuten/search': {
      id: '/api/rakuten/search'
      path: '/api/rakuten/search'
      fullPath: '/api/rakuten/search'
      preLoaderRoute: typeof ApiRakutenSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  RecommendationsRoute: RecommendationsRoute,
  SettingsRoute: SettingsRoute,
  TasteRoute: TasteRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  WorksExternalRoute: WorksExternalRoute,
  ApiRakutenItemRoute: ApiRakutenItemRoute,
  ApiRakutenSearchRoute: ApiRakutenSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
